spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 636409669842-iourh1e2pobbkbiu46jadl539enb31fm.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8082/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email

          kakao:
            client-id: 2f42b8424170676cbbc916b825953bc6
            redirect-uri: "http://localhost:8082/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email

          naver:
            client-id: iNxznHz27Vo8N9oX_60J
            client-secret: gX1MqV4nDS
            redirect-uri: "http://localhost:8082/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response